### ISSUE TITLE
No CDS annotation in SARS-CoV-2_parser

### ISSUE THREAD

**Issue by mvacher** [IBM/omxware-getting-started#3] opened 2023-04-13 01:36 UTC
First of all, thank you very much  for putting together this tool and making it available.

Following the ‘readme’, I could build the image and run the example (sequence: NC_045512.2) without any issues.
However, the resulting annotation file in GFF3 format contains only 2 lines of annotation (see below, FASTA sequence at the end was removed)
 
```
$ head outputs/NC_045512.2_annotated.gff                                                                                                                                                                      
##gff-version 3
##sequence-region NC_045512.2 1 29903
NC_045512.2     Infernal:001001 misc_RNA            13469    13550    81.6       +              .                ID=NC_045512.2_00001;Parent=NC_045512.2_00001_gene;Note="Coronavirus frameshifting stimulation element";accession=RF00507;inference=COORDINATES:profile:Infernal:001001;locus_tag=NC_045512.2_00001;product=Corona_FSE
NC_045512.2     Infernal:001001 misc_RNA            29727    29769    54.4       +              .                ID=NC_045512.2_00002;Parent=NC_045512.2_00002_gene;Note="Coronavirus 3' stem-loop II-like motif (s2m)";accession=RF00164;inference=COORDINATES:profile:Infernal:001001;locus_tag=NC_045512.2_00002;product=s2m
##FASTA
```
 
Is this the expected result ? I’ve tried other fasta sequences but the results were similar (1 or 2 annotation lines).
I was interested in annotating the CDS regions, but these are never present in the final gff.

Thanks

**Comment by bextra** [comment] 2024-06-04 17:46
We're adding the response here to the original poster for completeness:

April 25,2023
[SARS-CoV-2_parser.tar.gz](https://github.com/user-attachments/files/15568392/SARS-CoV-2_parser.tar.gz)


Hi Michael,
 
I’m sorry for the delay in responding. Looks like the covid19 reference we retrieve from uniport has some minor changes since we published. I believe the issue is now fixed. For some reason I don’t have permissions to our public github to write, so I’m giving you a tar.gz of the files. This version also contains a few unittests that run during the build of the container image. Once I can sort out the permissions issue we can push these changes to our github.
 
To build the image just execute the docker-build.sh script.
 
Regards,
 
Ed

**Closed by bextra** 2024-06-04 17:46 UTC
